# Copyright 2011-2012 The MathWorks, Inc.
# Autogenerated on: 21-Apr-2015 17:49:17
# Model: FULLDUPLEX
# MyTemplate
# File name: Fullduplex.mk
# Template: gmake 
# Template Version: 1.0 
# Tool Chain Configuration: stellaris_lp
# Tool Chain Configuration Version: 1.0

THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

MODEL_NAME := Fullduplex
HOST_PLATFORM := windows
BUILD_CFG := MW
TARGET_EXT := .out
OBJ_EXT := .obj
TOOL_CHAIN_CFG := stellaris_lp
FORMAT_PATH = $(if $(filter \\\\%,$(1)),"$(1)",$(subst $(SPACE),\$(SPACE),$(subst \,/,$(1))))

MATLAB_ROOT_RELATIVE := ..\..\..\..\..\..\..\Program Files\MATLAB\R2013a\#MATLAB_ROOT_RELATIVE_END
MATLAB_ROOT_ABSOLUTE := C:\Program Files\MATLAB\R2013a\#MATLAB_ROOT_ABSOLUTE_END
SOURCE_PATH := $(call FORMAT_PATH,.\)

OUTPUT_PATH := $(call FORMAT_PATH,$(SOURCE_PATH)$(BUILD_CFG)/)

DERIVED_PATH := $(call FORMAT_PATH,$(SOURCE_PATH))
TARGET_NAME_PREFIX := 
TARGET_NAME_POSTFIX := 
TARGET_FILE := $(TARGET_NAME_PREFIX)$(MODEL_NAME)$(TARGET_NAME_POSTFIX)$(TARGET_EXT)

TARGET := $(OUTPUT_PATH)$(TARGET_FILE)

#Code Generation Files

ifneq (.a,$(strip $(TARGET_EXT)))
SOURCE_FILES := $(call FORMAT_PATH,.\datapacket.c) $(call FORMAT_PATH,.\I2C_Stellaris_API.c) $(call FORMAT_PATH,.\reentrance.asm) $(call FORMAT_PATH,.\ringbuf.c) $(call FORMAT_PATH,.\rtiostreamserial_mp.c) $(call FORMAT_PATH,.\ssi_API.c) $(call FORMAT_PATH,.\startup_ccs.c) $(call FORMAT_PATH,.\stellaris_runtime.c) $(call FORMAT_PATH,.\uart_driver_mp.c) $(call FORMAT_PATH,.\uartx_driver.c) $(call FORMAT_PATH,.\xprintf.c) $(call FORMAT_PATH,.\Fullduplex.c) $(call FORMAT_PATH,.\Fullduplex_data.c) $(call FORMAT_PATH,.\ert_main.c)
else
SOURCE_FILES := $(call FORMAT_PATH,.\datapacket.c) $(call FORMAT_PATH,.\I2C_Stellaris_API.c) $(call FORMAT_PATH,.\reentrance.asm) $(call FORMAT_PATH,.\ringbuf.c) $(call FORMAT_PATH,.\rtiostreamserial_mp.c) $(call FORMAT_PATH,.\ssi_API.c) $(call FORMAT_PATH,.\startup_ccs.c) $(call FORMAT_PATH,.\stellaris_runtime.c) $(call FORMAT_PATH,.\uart_driver_mp.c) $(call FORMAT_PATH,.\uartx_driver.c) $(call FORMAT_PATH,.\xprintf.c) $(call FORMAT_PATH,.\Fullduplex.c) $(call FORMAT_PATH,.\Fullduplex_data.c) $(call FORMAT_PATH,.\ert_main.c)
endif

HEADER_FILES := $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\blocks\stellaris_lp_lct\datapacket.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\I2C_Stellaris_API.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\reentrance.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\ringbuf.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\ssi_API.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\stellaris_runtime.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\uart_driver_mp.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\uartx_driver.h) $(call FORMAT_PATH,..\..\..\..\..\..\..\MATLAB\SupportPackages\R2013a\StellarisLP\src\xprintf.h) $(call FORMAT_PATH,.\Fullduplex.h)

LIBRARY_FILES := 

OBJ_FILES := $(addprefix $(DERIVED_PATH),$(addsuffix $(OBJ_EXT),$(basename $(notdir $(SOURCE_FILES)))))

SKIPPED_FILES := 

#Code Generation Information

COMPILER_CODEGEN_ARGS := -I"C:/Users/jherr.ECE-REGROFF-D2/Downloads/Tiva UDP Demo/Tiva UDP Demo/matlab/Fullduplex_rtt" -I"C:/Users/jherr.ECE-REGROFF-D2/Downloads/Tiva UDP Demo/Tiva UDP Demo/matlab" -I"C:/Program Files/MATLAB/R2013a/extern/include" -I"C:/Program Files/MATLAB/R2013a/simulink/include" -I"C:/Program Files/MATLAB/R2013a/rtw/c/src" -I"C:/Program Files/MATLAB/R2013a/rtw/c/src/ext_mode/common" -I"C:/Program Files/MATLAB/R2013a/rtw/c/ert" -I"C:/MATLAB/SupportPackages/R2013a/StellarisLP/blocks/stellaris_lp_lct" -I"C:/MATLAB/SupportPackages/R2013a/StellarisLP/include" -I"C:/MATLAB/SupportPackages/R2013a/StellarisLP/src" -I"C:/MATLAB/SupportPackages/R2013a/StellarisWare_lite" -I"C:/MATLAB/SupportPackages/R2013a/ti_armcc/include" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 -mf4 --gcc -g --define="MODEL=Fullduplex" --define="NUMST=3" --define="NCSTATES=0" --define="HAVESTDIO=" --define="ONESTEPFCN=0" --define="TERMFCN=1" --define="MAT_FILE=0" --define="MULTI_INSTANCE_CODE=0" --define="INTEGER_CODE=0" --define="MT=0" --define="CLASSIC_INTERFACE=0" --define="TID01EQ=1" --define="PART_LM4F120H5QR=" --define="TARGET_IS_BLIZZARD_RA1=" --define="ccs=ccs" --define="UART_BUFFERED=1"

COMPILER_TCCFG_ARGS := -c
COMPILER_ARGS := $(COMPILER_CODEGEN_ARGS) $(COMPILER_TCCFG_ARGS)

LINKER_CODEGEN_ARGS :=  --stack_size=4096 --heap_size=4096 --reread_libs --rom_model "C:/MATLAB/SupportPackages/R2013a/StellarisLP/registry/stellaris_linkcmd" --define=TARGET_IS_BLIZZARD_RA1 -i"C:/MATLAB/SupportPackages/R2013a/ti_armcc/lib"  

LINKER_TCCFG_ARGS := -o $(TARGET)
LINKER_ARGS := $(LINKER_CODEGEN_ARGS) $(LINKER_TCCFG_ARGS)

PREBUILD_ARGS := 

POSTBUILD_ARGS := $(TARGET) $(OUTPUT_PATH)$(MODEL_NAME).bin "C:\MATLAB\SupportPackages\R2013a\ti_armcc\bin\armofd" "C:\MATLAB\SupportPackages\R2013a\ti_armcc\bin\armhex" "C:\MATLAB\SupportPackages\R2013a\StellarisLP\utils\tiobj2bin\mkhex4bin"

EXECUTE_ARGS := 



COMPILER ?= $(subst \,/,C:\MATLAB\SupportPackages\R2013a\ti_armcc\bin\armcl)

LINKER ?= $(subst \,/,C:\MATLAB\SupportPackages\R2013a\ti_armcc\bin\armlnk)

PREBUILD_TOOL ?= 

POSTBUILD_TOOL ?= $(subst \,/,C:\MATLAB\SupportPackages\R2013a\StellarisLP\utils\tiobj2bin\tiobj2bin.bat)

EXECUTE_USES_TARGET = off
ifeq (on,$(EXECUTE_USES_TARGET))
 EXECUTE_TOOL ?= $(TARGET)
else
 EXECUTE_TOOL ?= 
endif
ifeq (windows,$(HOST_PLATFORM))
 RM ?= del /q
else
 RM ?= rm -f
endif
ifeq (windows,$(HOST_PLATFORM))
 MKDIR ?= mkdir
else
 MKDIR ?= mkdir -p
endif

#Targets
.DEFAULT_GOAL := all

.PHONY : all execute prebuild build postbuild info environment check clean

all : execute

ifneq (,$(strip $(EXECUTE_TOOL)))
execute : build
	$(info "Evaluating execute target")
	"$(EXECUTE_TOOL)" $(EXECUTE_ARGS)
else
execute : build
endif

build : postbuild
	$(info "Evaluating build target")

ifneq (,$(strip $(PREBUILD_TOOL)))
ifneq (.a,$(strip $(TARGET_EXT)))
prebuild : | $(OUTPUT_PATH) $(DERIVED_PATH)
	$(info "Evaluating prebuild target")
	"$(PREBUILD_TOOL)" $(PREBUILD_ARGS)
    else
prebuild : | $(OUTPUT_PATH) $(DERIVED_PATH)
    endif
else
prebuild : | $(OUTPUT_PATH) $(DERIVED_PATH)
endif

ifneq (,$(strip $(POSTBUILD_TOOL)))
ifneq (.a,$(strip $(TARGET_EXT)))
postbuild : $(TARGET)
	$(info "Evaluating postbuild target")
	"$(POSTBUILD_TOOL)" $(POSTBUILD_ARGS)
    else
postbuild : $(TARGET)
    endif
else
postbuild : $(TARGET)
endif

ifneq (,$(strip $(LINKER)))
ifneq (.a,$(strip $(TARGET_EXT)))
$(TARGET) : prebuild $(OBJ_FILES)
	"$(LINKER)" $(OBJ_FILES) $(LIBRARY_FILES) $(LINKER_ARGS)
else
$(TARGET) : $(OBJ_FILES)
	"$(LINKER)" $(OBJ_FILES) $(LIBRARY_FILES) $(LINKER_ARGS)
endif

$(OBJ_FILES) : $(SOURCE_FILES) $(HEADER_FILES)
	"$(COMPILER)" $(COMPILER_ARGS) $(SOURCE_FILES)
else
$(TARGET) : prebuild $(SOURCE_FILES) $(HEADER_FILES)
	"$(COMPILER)" $(COMPILER_ARGS) $(SOURCE_FILES)
endif

$(OUTPUT_PATH) :
ifeq (,$(wildcard $(OUTPUT_PATH)))
	@$(MKDIR) "$(OUTPUT_PATH)"
endif

$(DERIVED_PATH) :
ifeq (,$(wildcard $(DERIVED_PATH)))
	@$(MKDIR) "$(DERIVED_PATH)"
endif

clean :
	-@$(RM) $(TARGET) $(OBJ_FILES)

info : 
	$(info MODEL_NAME=$(MODEL_NAME))
	$(info HOST_PLATFORM=$(HOST_PLATFORM))
	$(info BUILD_CFG=$(BUILD_CFG))
	$(info TOOL_CHAIN_CFG=$(TOOL_CHAIN_CFG))
	$(info TARGET_EXT=$(TARGET_EXT))
	$(info OBJ_EXT=$(OBJ_EXT))
	$(info SOURCE_PATH=$(SOURCE_PATH))
	$(info OUTPUT_PATH=$(OUTPUT_PATH))
	$(info DERIVED_PATH=$(DERIVED_PATH))
	$(info TARGET_FILE=$(TARGET_FILE))
	$(info TARGET=$(TARGET))
	$(info COMPILER=$(COMPILER))
	$(info COMPILER_ARGS=$(COMPILER_ARGS))
	$(info COMPILER_CODEGEN_ARGS=$(COMPILER_CODEGEN_ARGS))
	$(info COMPILER_TCCFG_ARGS=$(COMPILER_TCCFG_ARGS))
	$(info LINKER=$(LINKER))
	$(info LINKER_ARGS=$(LINKER_ARGS))
	$(info LINKER_CODEGEN_ARGS=$(LINKER_CODEGEN_ARGS))
	$(info LINKER_TCCFG_ARGS=$(LINKER_TCCFG_ARGS))
	$(info PREBUILD_TOOL=$(PREBUILD_TOOL))
	$(info PREBUILD_ARGS=$(PREBUILD_ARGS))
	$(info POSTBUILD_TOOL=$(POSTBUILD_TOOL))
	$(info POSTBUILD_ARGS=$(POSTBUILD_ARGS))
	$(info EXECUTE_TOOL=$(EXECUTE_TOOL))
	$(info EXECUTE_ARGS=$(EXECUTE_ARGS))
	$(info SOURCE_FILES=$(SOURCE_FILES))
	$(info HEADER_FILES=$(HEADER_FILES))
	$(info LIBRARY_FILES=$(LIBRARY_FILES))
	$(info OBJ_FILES=$(OBJ_FILES))
	$(info SKIPPED_FILES=$(SKIPPED_FILES))
	$(info RM=$(RM))
	$(info MKDIR=$(MKDIR))

environment :
	$(if $(findstring windows,$(HOST_PLATFORM)),$(info ENVIRONMENT=$(shell set)),$(info ENVIRONMENT=$(shell env)))
